### ISSUE TITLE
Project does not open in VS

### ISSUE THREAD

**Issue by attrib75** [microsoftgraph/uwp-csharp-meetingbot-sample#2] opened 2017-11-13 13:58 UTC
Error message:  Object reference not set to an instance of an object.

thanks

**Comment by jamescro** [comment] 2017-11-13 16:51
Thanks for raising this. I can't reproduce your issue, though. The project loads for me in both VS 2015 and VS 2017. Which version of VS are you running?

**Comment by attrib75** [comment] 2017-11-13 18:24
Thanks for responding. I receive this error when downloading zip, extracting, then opening solution.  I tried two separate zip downloads attempts.  I'm using VS 2017 15.4.0

**Comment by jamescro** [comment] 2017-11-13 20:56
Do you have the latest [Windows development tools](https://developer.microsoft.com/en-us/windows/downloads)? The project contains a Universal Windows Platform application.

**Comment by attrib75** [comment] 2017-11-14 22:05
Yes, I can open and run the [Intelligent Kiosk Sample](https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk) with no issues.   Its entirely possible I'm doing something wrong, but I'm just downloading a zip, extracting and opening the solution like any other

**Comment by jamescro** [comment] 2017-11-15 00:51
I updated my VS to 15.4.4 (was running 15.3, I think), and the solution loads for me. Could you check Tools -> Extensions and Updates for any required updates? After I upgraded, I don't see any other updates to my own extensions.

**Comment by jasonjoh** [comment] 2020-05-11 15:53
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. We apologize for any inconvenience.

**Closed as completed by jasonjoh** 2020-05-11 15:53 UTC
Labels: area: outlook, needs more info
